### PR TITLE
35 add auth to endpoints

### LINKED ISSUE #35: Gate creating/deleting/updating surveys behind login on the backend
For security reasons, we need to gate certain API endpoints behind login. When a user authenticates, we generate a Json Web Token (JWT) with their ID and return it in a `Set-Cookie` header. The browser then stores the cookie on the client side and sends it back with every request to the server. A valid JWT must be present in the requests to all endpoints that require authorization.

For this task, you'll need to (a) fix the `ensureRequestAuth` function to validate the presence of the JWT and (b) add an authentication check to the required endpoints.

See the NOTE section before you start.

## Part A
Modify `ensureRequestAuth` in `server/src/shared/AuthGateway.ts` to contain a check that would reject requests with missing JWT tokens. Below is an excerpt from the file:

```ts
export async function
    ensureRequestAuth(req: Request<any>, res: Response<any>, next: NextFunction) {
    const token = req.signedCookies[cookieProps.key];

    /*
        Replace this comment with the algorithm below:

        a) Check if the token is missing
        b) If it is:
            1) set the request status code to UNAUTHORIZED
            2) set the JSON error message to "JWT is missing"
            3) return from the function
    */

    try {
        const { id } = await jwtService.decodeJwt(token);
        req.userId = id;
        next();
    } catch (e) {
        res.status(UNAUTHORIZED).json({ error: "Invalid or expired JWT." });
    }
}
```

- [x] `ensureRequestAuth` rejects requests if the JWT is missing

## Part B
Modify the endpoints in the check list to use `ensureRequestAuth` as their first request handler. This can be done by providing `ensureRequestAuth` as a second argument to the routes you wish to modify. For example:

```ts
// This makes the endpoint `/mission-critical-endpoint` require authorization.
router.post('/mission-critical-endpoint', ensureRequestAuth, async (req, res, next) => { ... });
```

- [x] `/api/users/delete/:id` requires authentication
- [x] `/api/users/update/` requires authentication
- [x] `/api/surveys/create` requires authentication
- [x] ` /api/surveys/update` requires authentication
- [x] `/api/surveys/delete/:id` requires authentication

## NOTE
A branch has already been created for you: `35-add-auth-to-endpoints`. To access the branch, execute the commands below (you do not need to copy the dollar sign).
```
$ git pull
$ git checkout 35-add-auth-to-endpoints
```

Perform `git branch` to make sure that you're on the correct branch.

### PR DESCRIPTION
**Pull request by imtemp**
closes #35

### CODE REVIEW

File: server/src/shared/AuthGateway.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+        Replace this comment with the algorithm below:
+
+        a) Check if the token is missing
+        b) If it is:
+            1) set the request status code to UNAUTHORIZED
+            2) set the JSON error message to "JWT is missing"
+            3) return from the function
+    */
+    if(token == undefined){
+        res.status(UNAUTHORIZED).json({ error: "JWT is missing" });
```
Comment (optimalstrategy) [inline server/src/shared/AuthGateway.ts:27]: You didn't return from the function. Should have been:

```ts
return res.status(UNAUTHORIZED).json({ error: "JWT is missing" });
```

**Review by optimalstrategy — APPROVED** [review]
